"""add personal tables

Revision ID: eeb155d82577
Revises: '0004_add_journal_and_settings'
Create Date: 2026-02-06 08:42:41.824780
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'eeb155d82577'
down_revision = '0004_add_journal_and_settings'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personal_budgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('monthly_limit', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'category', name='uq_personal_budget_user_category')
    )
    op.create_index('ix_personal_budget_user', 'personal_budgets', ['user_id'], unique=False)
    op.create_table('personal_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('entry_type', sa.String(length=10), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('vendor', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('ai_categorized', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_personal_user_category', 'personal_entries', ['user_id', 'category'], unique=False)
    op.create_index('ix_personal_user_date', 'personal_entries', ['user_id', 'entry_date'], unique=False)
    op.alter_column('documents', 'metadata_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index(op.f('ix_doc_org_time'), table_name='documents')
    op.alter_column('ingestion_runs', 'upload_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('ingestion_runs', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('inventory_items', 'unit',
               existing_type=sa.VARCHAR(length=32),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_imv_org_time'), table_name='inventory_movements')
    op.create_index('ix_invmove_org_item_ts', 'inventory_movements', ['org_id', 'item_id', 'ts'], unique=False)
    op.alter_column('journal_days', 'parse_status',
               existing_type=sa.VARCHAR(length=16),
               server_default=None,
               existing_nullable=False)
    op.alter_column('journal_days', 'total_revenue',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               server_default=None,
               existing_nullable=False)
    op.alter_column('journal_days', 'total_cost',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               server_default=None,
               existing_nullable=False)
    op.alter_column('journal_days', 'net_profit',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               server_default=None,
               existing_nullable=False)
    op.alter_column('journal_days', 'clarification_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.add_column('journal_entries', sa.Column('payment_status', sa.String(length=20), nullable=False))
    op.add_column('journal_entries', sa.Column('payment_date', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('journal_entries', 'ambiguous',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('journal_entries', 'resolved',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('organisation_settings', 'total_initial_investment',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               server_default=None,
               existing_nullable=False)
    op.alter_column('organisation_settings', 'starting_cash_balance',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               server_default=None,
               existing_nullable=False)
    op.alter_column('organisation_settings', 'current_assets_value',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               server_default=None,
               existing_nullable=False)
    op.alter_column('organisation_settings', 'default_currency',
               existing_type=sa.VARCHAR(length=10),
               server_default=None,
               existing_nullable=False)
    op.alter_column('organisation_settings', 'default_locale',
               existing_type=sa.VARCHAR(length=10),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint(op.f('uq_organisations_name'), 'organisations', type_='unique')
    op.alter_column('subscriptions', 'org_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_sub_org_status'), table_name='subscriptions')
    op.add_column('transactions', sa.Column('payment_status', sa.String(length=20), nullable=False))
    op.add_column('transactions', sa.Column('payment_date', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('transactions', 'org_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('transactions', 'metadata_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=False)
    op.drop_index(op.f('ix_tx_org_ts'), table_name='transactions')
    op.alter_column('uploads', 'org_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_upload_org_status'), table_name='uploads')
    op.drop_index(op.f('ix_upload_org_time'), table_name='uploads')
    op.alter_column('users', 'org_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_users_org_email'), table_name='users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_org_email'), 'users', ['org_id', 'email'], unique=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('users', 'org_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_upload_org_time'), 'uploads', ['org_id', 'uploaded_at'], unique=False)
    op.create_index(op.f('ix_upload_org_status'), 'uploads', ['org_id', 'status'], unique=False)
    op.alter_column('uploads', 'org_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_tx_org_ts'), 'transactions', ['org_id', 'txn_date'], unique=False)
    op.alter_column('transactions', 'metadata_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('transactions', 'org_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('transactions', 'payment_date')
    op.drop_column('transactions', 'payment_status')
    op.create_index(op.f('ix_sub_org_status'), 'subscriptions', ['org_id', 'status'], unique=False)
    op.alter_column('subscriptions', 'org_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_unique_constraint(op.f('uq_organisations_name'), 'organisations', ['name'], postgresql_nulls_not_distinct=False)
    op.alter_column('organisation_settings', 'default_locale',
               existing_type=sa.VARCHAR(length=10),
               server_default=sa.text("'en'::character varying"),
               existing_nullable=False)
    op.alter_column('organisation_settings', 'default_currency',
               existing_type=sa.VARCHAR(length=10),
               server_default=sa.text("'USD'::character varying"),
               existing_nullable=False)
    op.alter_column('organisation_settings', 'current_assets_value',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=False)
    op.alter_column('organisation_settings', 'starting_cash_balance',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=False)
    op.alter_column('organisation_settings', 'total_initial_investment',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=False)
    op.alter_column('journal_entries', 'resolved',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('journal_entries', 'ambiguous',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.drop_column('journal_entries', 'payment_date')
    op.drop_column('journal_entries', 'payment_status')
    op.alter_column('journal_days', 'clarification_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('journal_days', 'net_profit',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=False)
    op.alter_column('journal_days', 'total_cost',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=False)
    op.alter_column('journal_days', 'total_revenue',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=False)
    op.alter_column('journal_days', 'parse_status',
               existing_type=sa.VARCHAR(length=16),
               server_default=sa.text("'pending'::character varying"),
               existing_nullable=False)
    op.drop_index('ix_invmove_org_item_ts', table_name='inventory_movements')
    op.create_index(op.f('ix_imv_org_time'), 'inventory_movements', ['org_id', 'ts'], unique=False)
    op.alter_column('inventory_items', 'unit',
               existing_type=sa.VARCHAR(length=32),
               server_default=sa.text("'unit'::character varying"),
               existing_nullable=False)
    op.alter_column('ingestion_runs', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('ingestion_runs', 'upload_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_doc_org_time'), 'documents', ['org_id', 'created_at'], unique=False)
    op.alter_column('documents', 'metadata_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index('ix_personal_user_date', table_name='personal_entries')
    op.drop_index('ix_personal_user_category', table_name='personal_entries')
    op.drop_table('personal_entries')
    op.drop_index('ix_personal_budget_user', table_name='personal_budgets')
    op.drop_table('personal_budgets')
    # ### end Alembic commands ###
